### ISSUE TITLE
sqlite3 Unable to Open Database File

### ISSUE THREAD

**Issue by geoffyli** [FelixKohlhas/ScreenFlux#1]
For sqlite3.connect(knowledge_db), exception has occurred: unable to open database file.

**Comment by ghost** [comment]
+1

**Comment by FelixKohlhas** [comment]
Thank you for trying my project, excuse my late reply. I have a feeling that this problem is permissions related. Could you please run `test -r "$HOME/Library/Application Support/Knowledge/knowledgeC.db"; echo "Exit Code: $?"` to check if  knowledgeC.db is readable and send me the result?
If the exit code is not 0, you can try granting the app that runs the script full disk access and test it again. In my case I am running it from iTerm, so I enabled its full disk access at `Privacy & Security > Full Disk Access`.
<img width="827" alt="Screenshot 2024-01-29 at 09 27 33" src="https://github.com/FelixKohlhas/ScreenFlux/assets/18424307/91dc9d5f-c4d3-405e-ba6a-a601d96cca3c">

**Comment by FelixKohlhas** [comment]
I have updated the code to provide more detailed error messages (in f42048c). Please try the new version of the script and send me the error messages if any occur.

**Comment by geoffyli** [comment]
It turns out that I was running the script in VSCode without giving full disk access to it. My bad, thank you for the help."
